$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:3
        },
        800:{
            items:4
        },
        1000:{
            items:4
        },
        1200:{
            items:5
        },
        1400:{
            items:6
        }
    }
})
